#%RAML 1.0 Library
usage: |
  Defines capabilities of PosPrinter device.

uses:
  commonCapabilities: common-capabilities-type.raml

types:
  CharactersPerLineCollection:
    description: |
      An array of possible characters per line.
    type: integer[]

  CharacterSetCollection:
    description: |
      An array of character sets.
    type: integer[]

  RotationCapabilityEnum:
    description: |
      Enumeration of supported rotations.
      Left90 - Object or text may be rotated 90° to the left.
        Unified POS 1 name: value L90.
      Right90 - Object or text may be rotated 90° to the right.
        Unified POS 1 name: value R90.
      Rotate180 - Object or text may be rotated 180° - upside down.
        Unified POS 1 name: value 180.
      Angle: - Object or text may be printed rotated at certain angle.
    type: string
    enum: ["Left90", "Right90", "Rotate180", "Angle"]

  RotationCollection:
    description: |
      Defines an array of rotation capabilities.
    type: RotationCapabilityEnum[]

  CustomColorCollection:
    description: |
      An array of possible custom colors.
    type: integer[]

  ColorCapabilityEnum:
    description: |
      Enumeration of color capabilities.
      Mono - Suppors only one color.
      TwoColor - Suppors two colors: primary and secondary.
      CustomColors - Suppors custom colors specified by CustomColorList.
      FullColor - Suppors full color mode.
      FullWithCustomColors - Suppors full color mode and custom colors.
    type: string
    enum: ["Mono", "TwoColor", "CustomColors", "FullColor", "FullWithCustomColors"]

  MarkSensedPaperFeedEnum:
    description: |
      Enumeration of mark sensed paper feed capabilities.
      Cutter - Feed the Mark Sensed paper to the auto-cutter cutting position.
        Unified POS 1 name: value PTR_MF_TO_CUTTER.
      CurrentTopOfForm - Feed the Mark Sensed paper to the present paper’s
        top of form. (Reverse feed if required)
        Unified POS 1 name: value PTR_MF_TO_CURRENT_TOF.
      NextTopOfForm - Feed the Mark Sensed paper to the paper’s next top
        of form.
        Unified POS 1 name: value PTR_MF_TO_NEXT_TOF.
      Takeup - Feed the Mark Sensed paper to the paper take-up position.
        Unified POS 1 name: value PTR_MF_TO_TAKEUP.
    type: string
    enum: ["Cutter", "CurrentTopOfForm", "NextTopOfForm", "Takeup"]

  MarkSensedPaperFeedCollection:
    description: |
      Defines an array of mark feed capabilities.
    type: MarkSensedPaperFeedEnum[]

  CartridgeSensorEnum:
    description: |
      Enumeration of cartridge sensor capabilities.
      Cleaning - There is a function to indicate that the head is being cleaned.
        Unified POS 1 name: value PTR_CART_CLEANING.
      Empty - There is a function to indicate that the Cartridge is empty.
        Unified POS 1 name: value PTR_CART_EMPTY.
      NearEnd - There is a function to indicate that the color Cartridge is
        near end.
        Unified POS 1 name: value PTR_CART_NEAREND.
      Removed - There is a function to indicate that the Cartridge has been
        removed.
        Unified POS 1 name: value PTR_CART_REMOVED.
    type: string
    enum: ["Cleaning", "Empty", "NearEnd", "Removed"]

  CartridgeSensorCollection:
    description: |
      Defines an array of cartridge sensor capabilities.
    type: CartridgeSensorEnum[]

  CharacterSetCapabilityEnum:
    description: |
      Enumeration of character set capability.
      Numeric - Character set supports numeric data, plus space, minus, and
        period.
      Alpha - Character set supports uppercase alphabetic plus numeric,
        space, minus, and period.
      Ascii - Character set supports all ASCII characters 0x20 through 0x7F.
      Kana - Character set supports partial code page 932, including ASCII
        characters 0x20 through 0x7F and the Japanese Kana characters 0xA1
        through 0xDF, but excluding the Japanese Kanji characters.
      Kanji - Character set supports code page 932, including the Shift-JIS
        Kanji characters, Levels 1 and 2.
      Unicode - Character set supports Unicode.
    type: string
    enum: [Numeric, Alpha, Ascii, Kana, Kanji, Unicode]

  FontTypefaceCollection:
    description: |
      Array of fonts/typefaces.
    type: string[]

  ReceiptStationCapabilities:
    description: |
      Capabilities of the receipt station.
    properties:
      bold:
        description: |
          Indicates if the receipt print station can print bold characters.
          Unified POS 1 name: property CapRecBold.
        type: boolean
        required: true
      italic:
        description: |
          Indicates if the receipt print station can print italic characters.
          Unified POS 1 name: property CapRecItalic.
        type: boolean
        required: true
      underline:
        description: |
          Indicates if the receipt print station can underline characters.
          Unified POS 1 name: property CapRecUnderline.
        type: boolean
        required: true
      fontTypefaceList:
        description: |
          Fonts and/or typefaces that are supported by the receipt station.
          The string consists of collection of font or typeface names.
          In Japan, this property will frequently include the fonts Mincho
          and Gothic. Other fonts or typefaces may be commonly supported in
          other countries. If this element is absent or contains an empty
          string then only the default typeface is supported.
          Unified POS 1 name: property FontTypefaceList.
        type: FontTypefaceCollection
      doubleHigh:
        description: |
          Indicates if the receipt station can print double high characters.
          Unified POS 1 name: property CapRecDhigh.
        type: boolean
        required: true
      doubleWide:
        description: |
          Indicates if the receipt station can print double wide characters.
          Unified POS 1 name: property CapRecDwide.
        type: boolean
        required: true
      doubleWideDoubleHigh:
        description: |
          Indicates if the receipt station can print double high/wide characters.
          Unified POS 1 name: property CapRecDwideDhigh.
        type: boolean
        required: true
      barCode:
        description: |
          Indicates if the receipt station has barcode printing capability.
          Unified POS 1 name: property CapRecBarCode.
        type: boolean
        required: true
      image:
        description: |
          Indicates if the receipt print station can print images.
          Unified POS 1 name: property CapRecBitmap.
        type: boolean
        required: true
      color:
        description: |
          Indicates the availability of receipt color cartridges.
          Unified POS 1 name: property CapRecColor. In Unified POS 1 the
          property contains values from Color and CustomColorList elements.
        type: ColorCapabilityEnum
        required: true
      customColors:
        description: |
          Device specific custom color cartridges for the receipt station.
          It is only provided if the property Color holds the values
          CustomColors or FullWithCustomColors.
          Unified POS 1 name: property CapRecColor. In Unified POS 1 the
          property contains values from Color and CustomColorList elements.
        type: CustomColorCollection
        required: false
      emptySensor:
        description: |
          Indicates if the receipt station has an out-of-paper sensor.
          Unified POS 1 name: property CapRecEmptySensor.
        type: boolean
        required: true
      nearEndSensor:
        description: |
          Indicates if the receipt station has a low paper sensor.
          Unified POS 1 name: property CapRecNearEndSensor.
        type: boolean
        required: true
      cartridgeSensors:
        description: |
          Collection of cartridge monitoring sensors at the receipt station.
          Unified POS 1 name: property CapRecCartridgeSensor.
        type: CartridgeSensorCollection
        required: false
      markSensedPaperFeeds:
        description: |
          Collection of mark sernsed paper feeds supported by receipt station.
          Unified POS 1 name: property CapRecMarkFeed.
        types: MarkSensedPaperFeedCollection
        required: false
      paperCut:
        description: |
          Indicates if the receipt station can perform paper cuts.
          Unified POS 1 name: property CapRecPapercut.
        type: boolean
        required: true
      stamp:
        description: |
          Indicates if the receipt has a stamp capability.
          Unified POS 1 name: property CapRecStamp.
        type: boolean
        required: true
      textRotations:
        description: |
          Supported text rotations of the receipt print station.
          This property was not available in Unified POS 1. It combines
          the following capabilities from UnifiedPOS 1:
          CapRecLeft90, CapRecRight90, CapRecRotate180.
          An empty collection or absence of the property indicates that
          text rotaion is not supported at this station.
        type: RotationCollection
        required: false
      barCodeRotations:
        description: |
          Supported barcode rotations of the receipt print station.
          An empty collection or absence of the property indicates that
          bar code rotaion is not supported at this station.
          Unified POS 1 name: property RecBarCodeRotationList.
        type: RotationCollection
        required: false
      imageRotations:
        description: |
          Supported image rotations of the receipt print station.
          An empty collection or absence of the property indicates that
          bar code rotaion is not supported at this station.
          Unified POS 1 name: property RecBitmapRotationList.
        type: RotationCollection
        required: false
      charactersPerLineWidths:
        description: |
          Supported widths in terms of characters per line by the station.
          Unified POS 1 name: property RecLineCharsList.
        type: CharactersPerLineCollection
        required: false
      horizontalRuledLine:
        description: |
          Indicates if horizontal ruled line is supported by the station.
          Unified POS 1 name: CapRecRuledLine value PTR_RL_HORIZONTAL
        type: boolean
        required: true
      verticalRuledLine:
        description: |
          Indicates if vertical ruled line is supported by the station.
          Unified POS 1 name:  CapRecRuledLine value PTR_RL_VERTICAL.
        type: boolean
        required: true

  JournalStationCapabilities:
    description: |
      Capabilities of the journal station.
    properties:
      bold:
        description: |
          Indicates if the journal print station can print bold characters.
          Unified POS 1 name: property CapJrnBold.
        type: boolean
        required: true
      italic:
        description: |
          Indicates if the journal print station can print italic characters.
          Unified POS 1 name: property CapJrnItalic.
        type: boolean
        required: true
      underline:
        description: |
          Indicates if the journal print station can underline characters.
          Unified POS 1 name: property CapJrnUnderline.
        type: boolean
        required: true
      doubleHigh:
        description: |
          Indicates if the journal station can print double high characters.
          Unified POS 1 name: property CapJrnDhigh.
        type: boolean
        required: true
      doubleWide:
        description: |
          Indicates if the journal station can print double wide characters.
          Unified POS 1 name: property CapJrnDwide.
        type: boolean
        required: true
      doubleWideDoubleHigh:
        description: |
          Indicates if the journal station can print double high/wide characters.
          Unified POS 1 name: property CapJrnDwideDhigh.
        type: boolean
        required: true
      color:
        description: |
          Indicates the availability of journal color cartridges.
          Unified POS 1 name: property CapRecColor. In Unified POS 1 the
          property contains values from Color and CustomColorList elements.
        type: ColorCapabilityEnum
        required: true
      customColors:
        description: |
          Device specific custom color cartridges for the journal station.
          It is only provided if the property Color holds the values
          CustomColors or FullWithCustomColors.
          Unified POS 1 name: property CapJrnColor. In Unified POS 1 the
          property contains values from Color and CustomColorList elements.
        type: CustomColorCollection
        required: false
      emptySensor:
        description: |
          Indicates if the journal station has an out-of-paper sensor.
          Unified POS 1 name: property CapJrnEmptySensor.
        type: boolean
        required: true
      nearEndSensor:
        description: |
          Indicates if the journal station has a low paper sensor.
          Unified POS 1 name: property CapJrnNearEndSensor.
        type: boolean
        required: true
      cartridgeSensors:
        description: |
          Collection of cartridge monitoring sensors at the journal station.
          Unified POS 1 name: property CapJrnCartridgeSensor.
        type: CartridgeSensorCollection
        required: false
      charactersPerLineWidths:
        description: |
          Supported widths in terms of characters per line by the station.
          Unified POS 1 name: property JrnLineCharsList.
        type: CharactersPerLineCollection
        required: false

  SlipStationCapabilities:
    description: |
      Capabilities of the slip station.
    properties:
      bold:
        description: |
          Indicates if the slip print station can print bold characters.
          Unified POS 1 name: property CapSlpBold.
        type: boolean
        required: true
      italic:
        description: |
          Indicates if the slip print station can print italic characters.
          Unified POS 1 name: property CapSlpItalic.
        type: boolean
        required: true
      underline:
        description: |
          Indicates if the slip print station can underline characters.
          Unified POS 1 name: property CapSlpUnderline.
        type: boolean
        required: true
      fontTypefaceList:
        description: |
          Fonts and/or typefaces that are supported by the slip station.
          The string consists of collection of font or typeface names.
          In Japan, this property will frequently include the fonts Mincho
          and Gothic. Other fonts or typefaces may be commonly supported in
          other countries. If this element is absent or contains an empty
          string then only the default typeface is supported.
          Unified POS 1 name: property FontTypefaceList.
        type: FontTypefaceCollection
      doubleHigh:
        description: |
          Indicates if the slip station can print double high characters.
          Unified POS 1 name: property CapSlpDhigh.
        type: boolean
        required: true
      doubleWide:
        description: |
          Indicates if the slip station can print double wide characters.
          Unified POS 1 name: property CapSlpDwide.
        type: boolean
        required: true
      doubleWideDoubleHigh:
        description: |
          Indicates if the slip station can print double high/wide characters.
          Unified POS 1 name: property CapSlpDwideDhigh.
        type: boolean
        required: true
      barCode:
        description: |
          Indicates if the slip station has barcode printing capability.
          Unified POS 1 name: property CapSlpBarCode.
        type: boolean
        required: true
      image:
        description: |
          Indicates if the slip print station can print images.
          Unified POS 1 name: property CapSlpBitmap.
        type: boolean
        required: true
      color:
        description: |
          Indicates the availability of slip color cartridges.
          Unified POS 1 name: property CapSlpColor. In Unified POS 1 the
          property contains values from Color and CustomColorList elements.
        type: ColorCapabilityEnum
        required: true
      customColors:
        description: |
          Device specific custom color cartridges for the slip station.
          It is only provided if the property Color holds the values
          CustomColors or FullWithCustomColors.
          Unified POS 1 name: property CapSlpColor. In Unified POS 1 the
          property contains values from Color and CustomColorList elements.
        type: CustomColorCollection
        required: false
      emptySensor:
        description: |
          Indicates if the slip station has an out-of-paper sensor.
          Unified POS 1 name: property CapSlpEmptySensor.
        type: boolean
        required: true
      nearEndSensor:
        description: |
          Indicates if the slip station has a low paper sensor.
          Unified POS 1 name: property CapSlpNearEndSensor.
        type: boolean
        required: true
      cartridgeSensors:
        description: |
          Collection of cartridge monitoring sensors at the slip station.
          Unified POS 1 name: property CapSlpCartridgeSensor.
        type: CartridgeSensorCollection
        required: false
      textRotations:
        description: |
          Supported text rotations of the slip print station.
          This property was not available in Unified POS 1. It combines
          the following capabilities from UnifiedPOS 1:
          CapSlpLeft90, CapSlpRight90, CapSlpRotate180.
          An empty collection or absence of the property indicates that
          text rotaion is not supported at this station.
        type: RotationCollection
        required: false
      barCodeRotations:
        description: |
          Supported barcode rotations of the slip print station.
          An empty collection or absence of the property indicates that
          bar code rotaion is not supported at this station.
          Unified POS 1 name: property SlpBarCodeRotationList.
        type: RotationCollection
        required: false
      imageRotations:
        description: |
          Supported image rotations of the slip print station.
          An empty collection or absence of the property indicates that
          bar code rotaion is not supported at this station.
          Unified POS 1 name: property SlpBitmapRotationList.
        type: RotationCollection
        required: false
      charactersPerLineWidths:
        description: |
          Supported widths in terms of characters per line by the station.
          Unified POS 1 name: property SlpLineCharsList.
        type: CharactersPerLineCollection
        required: false
      bothSidesPrint:
        description: |
          Indicates if slip station can print on both sides of the form.
          It can be done either by flipping the form or by using dual
          print heads.
          Unified POS 1 name: property CapSlpBothSidesPrint
        type: boolean
        required: true
      fullSlip:
        description: |
          Indicates if slip station can print full length forms.
          If false, then the slip is a "validation" type station. This usually
          limits the number of print lines, and disables access to the receipt
          and/or journal stations while the validation slip is being used.
          Unified POS 1 name: property CapSlpFullslip.
        type: boolean
        required: true
      horizontalRuledLine:
        description: |
          Indicates if horizontal ruled line is supported by the station.
          Unified POS 1 name: CapSlpRuledLine value PTR_RL_HORIZONTAL
        type: boolean
        required: true
      verticalRuledLine:
        description: |
          Indicates if vertical ruled line is supported by the station.
          Unified POS 1 name:  CapSlpRuledLine value PTR_RL_VERTICAL.
        type: boolean
        required: true

  PosPrinterCapabilities:
    description: |
      Capabilities of the PosPrinter device category.
    properties:
      commonCapabilities:
        description: |
          Common capabilities for all device categories.
        type: commonCapabilities.CommonCapabilities
        required: true
      coverSensor:
        description: |
          Indicates if printer has cover sensor.
          Unified POS 1 name: property CapCoverSensor.
        type: boolean
        required: true
      mapCharacterSet:
        description: |
          Indicates if printer can map character sets.
          If MapCharacterSet is true, then the Service is able to map
          the characters of the application to the character sets defined
          in CharacterSetList.
          Unified POS 1 name: property CapMapCharacterSet.
        type: boolean
        required: true
      defaultCharacterSetCapability:
        description: |
          The default character set capability of the POS printer device.
          Unified POS 1 name: property CapCharacterSet.
        type: CharacterSetCapabilityEnum
        required: false
      characterSetList:
        description: |
          List of character set numbers.
          Unified POS 1 name: CharacterSetList property.
        type: CharacterSetCollection
        required: false
      receiptStationPresent:
        description: |
          Indicates if receipt print station is present.
          Unified POS 1 name: property CapRecPresent.
        type: boolean
        required: true
      journalStationPresent:
        description: |
          Indicates if journal print station is present.
          Unified POS 1 name: property CapJrnPresent.
        type: boolean
        required: true
      slipStationPresent:
        description: |
          Indicates if slip print station is present.
          Unified POS 1 name: property CapSlpPresent.
        type: boolean
        required: true
      receiptStationCapabilities:
        description: |
          Capabilities of the receipt station.
          This property was not available in Unified POS 1.
          It aggregates at least all capabilities from UnifiedPOS 1 starting
          with prefix "CapRec".
        type: ReceiptStationCapabilities
        required: false
      journalStationCapabilities:
        description: |
          Capabilities of the journal station.
          This property was not available in Unified POS 1.
          It aggregates at least all capabilities from UnifiedPOS 1 starting
          with prefix "CapJrn".
        type: JournalStationCapabilities
        required: false
      slipStationCapabilities:
        description: |
          Capabilities of the slip station.
          This property was not available in Unified POS 1.
          It aggregates at least all capabilities from UnifiedPOS 1 starting
          with prefix "CapSlp".
        type: SlipStationCapabilities
        required: false
